<?php

namespace SP\ImportBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * S1VenuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class S1VenuesRepository extends EntityRepository
{
    public function findAllIds()
    {
        $queryBuilder = $this->createQueryBuilder('v')
                            ->select('v.venueId')
                            ->orderBy('v.venueId', 'ASC');
        return $queryBuilder->getQuery()->getResult();
    }

    public function findLocationByVenueId($venueId)
    {
        $qb = $this->createQueryBuilder('v')
                    ->select('v.locationId')
                    ->where('v.venueId = :venueId')
                    ->setParameter('venueId', $venueId);

        $location = $qb->getQuery()->getSingleResult();
        return $location['locationId'];
    }
}


