<?php

namespace SP\ImportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * S1VenuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class S1VenuesRepository extends EntityRepository
{
    public function getByVenueId($venueId)
    {

    }
}
